import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Customer } from '@/data/mock';
import { formatCurrency, formatDate } from '@/data/format';

function esc(s?: string): string {
  return (s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string));
}

/** Build a branded HTML account statement for a customer's khata. */
export function buildStatementHtml(customer: Customer, opts: { companyName: string }): string {
  const totalGave = customer.ledger.reduce((s, e) => s + e.debit, 0);
  const totalGot = customer.ledger.reduce((s, e) => s + e.credit, 0);
  const bal = customer.balance;
  const balLabel = bal === 0 ? 'Settled up' : bal > 0 ? "You'll get" : "You'll give";
  const balColor = bal === 0 ? '#64748b' : bal > 0 ? '#0F9D58' : '#E11D48';
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const rows =
    customer.ledger
      .map((e) => {
        const gave = e.debit > 0;
        return `<tr>
          <td>${formatDate(e.date)}</td>
          <td>${esc(e.memo)}</td>
          <td class="r red">${gave ? formatCurrency(e.debit) : '—'}</td>
          <td class="r green">${!gave ? formatCurrency(e.credit) : '—'}</td>
          <td class="r bold">${formatCurrency(Math.abs(e.balance))}</td>
        </tr>`;
      })
      .join('') || '<tr><td colspan="5" style="text-align:center;color:#8a8fb4;padding:28px;">No transactions yet</td></tr>';

  return `<!doctype html><html><head><meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    * { box-sizing: border-box; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    body { font-family: -apple-system, 'Helvetica Neue', Roboto, Arial, sans-serif; color: #0E1130; margin: 0; }
    .head { background: linear-gradient(135deg, #4F46E5, #06B6D4); color: #fff; padding: 28px 32px; }
    .brand { font-size: 13px; letter-spacing: 1.5px; text-transform: uppercase; opacity: .9; }
    .title { font-size: 26px; font-weight: 800; margin-top: 6px; }
    .sub { font-size: 13px; opacity: .85; margin-top: 2px; }
    .wrap { padding: 28px 32px; }
    .row { display: flex; justify-content: space-between; align-items: flex-start; }
    .label { color: #8A8FB4; font-size: 11px; text-transform: uppercase; letter-spacing: .6px; }
    .val { font-size: 16px; font-weight: 700; }
    .muted { color: #565B83; font-size: 13px; margin-top: 2px; }
    .bal { font-size: 30px; font-weight: 800; }
    .cards { display: flex; gap: 16px; margin: 22px 0 8px; }
    .card { flex: 1; background: #F4F5FB; border-radius: 12px; padding: 14px 16px; }
    table { width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 13px; }
    th { text-align: left; color: #8A8FB4; font-size: 10px; letter-spacing: .5px; text-transform: uppercase; border-bottom: 2px solid #E6E7F4; padding: 9px 6px; }
    td { padding: 11px 6px; border-bottom: 1px solid #EEEFF8; }
    .r { text-align: right; font-variant-numeric: tabular-nums; }
    .bold { font-weight: 700; }
    .red { color: #E11D48; } .green { color: #0F9D58; }
    .foot { margin-top: 28px; color: #8A8FB4; font-size: 11px; text-align: center; }
  </style></head>
  <body>
    <div class="head">
      <div class="brand">${esc(opts.companyName)}</div>
      <div class="title">Account Statement</div>
      <div class="sub">${today}</div>
    </div>
    <div class="wrap">
      <div class="row">
        <div>
          <div class="label">Customer</div>
          <div class="val">${esc(customer.name)}</div>
          <div class="muted">${esc([customer.company, customer.phone, customer.email].filter(Boolean).join(' · '))}</div>
        </div>
        <div style="text-align:right;">
          <div class="label">${balLabel}</div>
          <div class="bal" style="color:${balColor};">${formatCurrency(Math.abs(bal))}</div>
        </div>
      </div>
      <div class="cards">
        <div class="card"><div class="label">Total you gave</div><div class="val red">${formatCurrency(totalGave)}</div></div>
        <div class="card"><div class="label">Total you got</div><div class="val green">${formatCurrency(totalGot)}</div></div>
      </div>
      <table>
        <thead><tr><th>Date</th><th>Details</th><th class="r">You Gave</th><th class="r">You Got</th><th class="r">Balance</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <div class="foot">Generated by Vantage · ${today}</div>
    </div>
  </body></html>`;
}

/** Render the statement to a PDF and open the OS share sheet (WhatsApp, email, etc.). */
export async function shareStatement(customer: Customer, opts: { companyName: string }): Promise<void> {
  const html = buildStatementHtml(customer, opts);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `${customer.name} — Statement`,
      UTI: 'com.adobe.pdf',
    });
  }
}
